### PR TITLE
Fix MSVC support to actually work and consider library paths too

### PR DESCRIPTION
**Pull request by sdroege**
See https://github.com/alexcrichton/pkg-config-rs/issues/59#issuecomment-407313044

cc @ferjm

### CODE REVIEW

**Comment by sdroege** [comment]
Thanks! Once @ferjm confirms that this also solves the problem on their side, can you do a new release for this?

**Comment by alexcrichton** [comment]
Sounds good to me!

**Comment by sdroege** [comment]
If there's anything broken by this, just let @ me in the issue :)

Thanks for the release

**Comment by alexcrichton** [comment]
Sure thing! BTW if you're willing I'd love to have some help maintaining this crate, so I don't mind adding you as a maintainer too!

**Comment by alexcrichton** [comment]
Sounds good to me!

**Comment by sdroege** [comment]
Thanks :)

**Pull request merged**
