### PR TITLE
update to recent rust changes

### PR DESCRIPTION
**Pull request by suhr**
Subj.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I'll merge as soon as a new nightly lands

**Comment by raymontag** [comment]
Having a project depening on a crate using pkg-config, how can I temporarily use suhrs source?

**Comment by alexcrichton** [comment]
@raymontag you should be able to use [overrides](http://doc.crates.io/guide.html#overriding-dependencies) in the future.

**Comment by raymontag** [comment]
Ok, thx :)

**Pull request merged**
