### PR TITLE
Expose env vars pkg-config depends on

### PR DESCRIPTION
**Pull request by pornel**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I wonder, this may need to be opt-in for now? Consumer libraries may not currently be prepared for this if they're using `pkg-config` otherwise with a different fallback. I'd imagine for a 1.0 release we'd do this by default but for now with the same 0.1 release I'm thinking we may want to stick to being conservative?

**Comment by pornel** [comment]
How can a consumer be not prepared for this?

I assume it has no effect in older versions of Cargo, so won't cause back compat problems.

And I assume it only causes rebuild when Cargo sees the env var change, so it's a bug fix for builds that weren't rebuilt, and the worst thing that can happen is that Cargo will rebuild the project too often.

**Comment by alexcrichton** [comment]
Ah so the problem here is that if you use pkg-config to locate a library and then use `cc` the crate to compile some support code, that build script won't get rerun when the C code changes. By default the `cc` crate doesn't print out the `rerun-if-used` annotations, so this could technically be a breaking change for that specific situation or situations like that

**Comment by pornel** [comment]
Oh, so the `rerun-if-env-changed` annotation *replaces* default file-based checks, instead of just adding one more check?

**Comment by alexcrichton** [comment]
Right yeah, Cargo's got a default "when do I rerun the build script" heuristic which is quite conservative by default, and printing *anything* as a dependency will replace this heuristic

**Pull request closed without merging**
