### PR TITLE
Rerun on PKG_CONFIG_PATH changes

### PR DESCRIPTION
**Pull request by sfackler**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! This was also proposed in https://github.com/alexcrichton/pkg-config-rs/pull/45 with some discussion there. tl;dr; I'm fine adding this, but for semver compatibility I'd prefer if it were off by default (with an option to turn on)

**Comment by sfackler** [comment]
Are you thinking a cargo feature as the toggle? I should also probably extend it to all of the environment variables it pokes at.

**Comment by sfackler** [comment]
(I had no complaints after doing this in a minor version bump in rust-openssl, for the record) :P

**Comment by alexcrichton** [comment]
Oh I'm just thinking like a boolean builder method.

I see pkg-config as very different than rust-openssl. For example I'm not embedding the openssl-sys build script but pkg-config is embedded in everyone's build script. (the linked #45 has more discussion on this)

**Comment by sfackler** [comment]
Ah gotcha, that makes sense. I didn't realize the implications of the rerun things.

**Comment by alexcrichton** [comment]
Yeah it's unfortunately subtle :(

**Comment by sfackler** [comment]
Updated

**Comment by alexcrichton** [comment]
Hm I don't think this includes `PKG_CONFIG_PATH`, does it?

**Comment by sfackler** [comment]
Oh right we need to check for that explicitly. Fixed!

**Pull request merged**
